# Generated by Django 4.1.3 on 2022-11-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_auto_20221115_2002"),
        ("reviews", "0003_auto_20221115_2033"),
    ]

    operations = []
