# Generated by Django 4.1.3 on 2022-11-16 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_merge_0003_auto_20221115_2002_0003_auto_20221115_2033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[\\w.@+-]+$")
                ],
            ),
        ),
    ]
