# Generated by Django 3.2.16 on 2022-11-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_categories_genres_reviews_titles'),
        ('reviews', '0005_alter_user_username'),
    ]

    operations = [
    ]
